backend:
  name: git-gateway
  branch: master

media_folder: "public/static/uploads"
public_folder: "static/uploads"

collections:
  - name: "question"
    label: "Question"
    folder: content/collections"
    create: true
    slug: "{{slug}}"
    identifier_field: "question"
    fields:
      - { label: "Question", name: "question", widget: "string" }
      - { label: "a", name: "a", widget: "string" }
      - { label: "b", name: "b", widget: "string" }
      - { label: "c", name: "c", widget: "string" }